language: php

os:
  - linux

dist: bionic

services:
  - mysql
  - postgresql
  - docker

addons:
  postgresql: "9.6"

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.nvm

php:
 - 7.4

env:
  - DB=pgsql MOODLE_BRANCH=master

before_install:
  - phpenv config-rm xdebug.ini
  - cd ../..
  - composer create-project -n --no-dev --prefer-dist moodlehq/moodle-plugin-ci ci ^3
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - moodle-plugin-ci install

script:
  - moodle-plugin-ci phplint
  - moodle-plugin-ci phpcpd
  - moodle-plugin-ci phpmd
  - moodle-plugin-ci phpdoc
  - moodle-plugin-ci codechecker
  - moodle-plugin-ci validate
  - moodle-plugin-ci savepoints
  - moodle-plugin-ci mustache 
  - moodle-plugin-ci grunt || true
  - moodle-plugin-ci phpunit --coverage-text --coverage-clover
  - moodle-plugin-ci behat
  - moodle-plugin-ci behat --profile chrome

after_success:
  - moodle-plugin-ci coveralls-upload
